version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    ports:
      - "${VITE_HOST}:${VITE_PORT}:${VITE_PORT}"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/