version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    ports:
      - 127.0.0.1:${VITE_PORT}:${VITE_PORT}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/