version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    ports:
      - "${VITE_HOST}:${VITE_PORT}:${VITE_PORT}"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx.dockerfile
    ports:
      - "${VITE_HOST}:${VITE_PORT}:80"
    depends_on:
      - build
    volumes:
      - ./dist:/var/www/html/public
  build:
    build:
      context: .
      dockerfile: ./.docker/build.dockerfile
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/